backend:
  name: git-gateway
  branch: main
local_backend: true
media_folder: /public/images
public_folder: /images

# ==========
# PRODUCTS
# ==========
collections:
  - name: products
    label: Products
    create: true
    delete: true
    format: json
    folder: public/content/products
    media_folder: '{{media_folder}}/products'
    public_folder: '{{public_folder}}/products'
    slug: '{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}-{{slug}}/index.json'
    fields:
      - { label: 'Hidden', name: 'hidden', widget: 'boolean', default: false, required: false }
      - { label: 'Discount', name: 'discount', widget: 'number', min: 0, max: 100 }
      - { label: 'Price', name: 'price', widget: 'number', value_type: 'float', min: 0 }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Created at', name: 'createdAt', widget: 'datetime' }
      - { label: 'Image Preview', name: 'imagePreview', widget: 'image', required: true }
      - { label: 'Category', name: 'category', widget: 'select', options: ['shirts', 'hats'] }
      - { label: 'Description', name: 'description', widget: 'markdown' }
      - label: 'Images'
        name: 'images'
        widget: 'list'
        default: []
        required: true
        min: 1
        field: {
            label: 'Image',
            name: 'image',
            widget: 'image',
            required: true,
          }
      - label: Options
        name: options
        widget: object
        fields:
          - label: Sizes
            name: Sizes
            widget: list
            summary: '{{fields.size}}'
            field: { label: Size, name: size, widget: select, options: ['sx', 's', 'm',  'l',  'xl',  'xxl', xxxl] }
          - label: Colors
            name: colors
            widget: list