# backend:
#   name: git-gateway
#   branch: main
backend:
  name: github
  repo: antklim89/cozy_clothes 
  branch: main
local_backend: true
media_folder: /public/images
public_folder: /images
editor:
  preview: false

collections:
# ==========
# PRODUCTS
# ==========
  - name: products
    label: Products
    create: true
    delete: true
    format: json
    folder: public/content/products
    media_folder: '{{media_folder}}/products'
    public_folder: '{{public_folder}}/products'
    slug: '{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}-{{slug}}'
    fields:
      - { label: 'Hidden', name: 'hidden', widget: 'boolean', default: false, required: false }
      - { label: 'Discount', name: 'discount', widget: 'number', min: 0, max: 100 }
      - { label: 'Price', name: 'price', widget: 'number', value_type: 'float', min: 0 }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Created at', name: 'createdAt', widget: 'datetime' }
      - { label: 'Image Preview', name: 'imagePreview', widget: 'image', required: true, allow_multiple: false }
      - { label: 'Category', name: 'category', widget: 'select', options: ['shirts', 'hats'] }
      - { label: 'Description', name: 'description', widget: 'markdown' }
      - label: 'Images'
        name: 'images'
        widget: 'list'
        default: []
        required: true
        min: 1
        field: {
            label: 'Image',
            name: 'image',
            widget: 'image',
            required: true,
          }
      - label: Options
        name: options
        widget: object
        fields:
          - label: Sizes
            name: sizes
            widget: list
            summary: '{{fields.size}}'
            field: { label: Size, name: size, widget: select, options: ['sx', 's', 'm',  'l',  'xl',  'xxl', xxxl] }
          - label: Colors
            name: colors
            widget: list
            fields:
              - { label: Name, name: name, widget: string, required: true }
              - { label: Code, name: code, widget: string, required: true }
    
# ==========
# CONTACTS
# ==========
  - name: contacts
    label: Contacts
    create: true
    delete: true
    format: json
    folder: public/content/contacts
    media_folder: '{{media_folder}}/contacts'
    public_folder: '{{public_folder}}/contacts'
    identifier_field: name
    slug: '{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}-{{slug}}'
    fields:
      - { label: 'Hidden', name: 'hidden', widget: 'boolean', default: false, required: false }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'E-mail', name: 'email', widget: 'string', required: true }
      - { label: 'Phone number', name: 'phone', widget: 'string', required: true }
    
# ==========
# TESTIMONIALS
# ==========
  - name: testimonials
    label: Testimonials
    create: true
    delete: true
    format: json
    folder: public/content/testimonials
    media_folder: '{{media_folder}}/testimonials'
    public_folder: '{{public_folder}}/testimonials'
    identifier_field: name
    slug: '{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}-{{slug}}'
    fields:
      - { label: 'Hidden', name: 'hidden', widget: 'boolean', default: false, required: false }
      - { label: 'Author Image', name: 'image', widget: 'image', required: true, allow_multiple: false }
      - { label: 'Text', name: 'text', widget: 'text', required: true }
      - { label: 'Author Name', name: 'name', widget: 'string', required: true }

# ==========
# SITE
# ==========
  - name: site
    label: Site
    media_folder: '{{media_folder}}/hero'
    public_folder: '{{public_folder}}/hero'
    files:
      - label: Hero
        name: hero
        file: public/content/hero.json
        fields:
          - { label: Text, name: text, widget: markdown, required: true }
          - { label: Image Preview, name: imagePreview, widget: image, required: true, allow_multiple: false }